name: Build .NET App

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x # or 8.0.x / 7.0.x depending on your project

      - name: Restore dependencies
        run: dotnet restore

      - name: Build without tests
        run: dotnet build --configuration Release --no-restore
